### ISSUE TITLE
File management

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/userbot_telegram#24]
I need a tool to send quickly files on Telegram automatically with a command like ```/send <filename>``` 

I only have to read how the ```os``` module works.

**Comment by MasterCruelty** [comment]
@archetipico do you ever used that module?

**Comment by archetipico** [comment]
yes, why?

**Comment by MasterCruelty** [comment]
> yes, why?
> 

If i'm not wrong when you initialize ```os.system()``` the default Path is ~ and not the path of the pyhton source file. 

Is there a method to say to ```os``` to use the same path without write it everytime?

**Comment by archetipico** [comment]
`os.system( arg )` is used to run commands, I think you are referring to `os.getcwd()`

**Comment by MasterCruelty** [comment]
> `os.system( arg )` is used to run commands, I think you are referring to `os.getcwd()`

Probably, as I said i'm not expert of this module.
So if I use ```os.getcwd()``` It returns the directory path of the python source file?

**Comment by archetipico** [comment]
It's used to return the Current Working Directory (`cwd`)

**Comment by MasterCruelty** [comment]
> It's used to return the Current Working Directory (`cwd`)

Ok so if I do something like:

```ruby
cwd = os.getcwd()
os.system("cd " + cwd)
os.system("zip -r <filename>.zip <arguments>")
```

Will it work?

**Comment by archetipico** [comment]
I honestly never tried it. Why don't you `os.system( "zip -r {}/file.zip args".format( os.getcwd() ) )`?

**Comment by MasterCruelty** [comment]
> I honestly never tried it. Why don't you `os.system( "zip -r {}/file.zip args".format( os.getcwd() ) )`?

It looks pretty good. What the {} stands for before the ```/file.zip```

**Comment by archetipico** [comment]
Simple [Python string formatting](https://www.w3schools.com/python/ref_string_format.asp)

**Comment by MasterCruelty** [comment]
> Simple [Python string formatting](https://www.w3schools.com/python/ref_string_format.asp)

pretty clear. Easier than expected, I'll use this approach as soon as I'll have the time

**Comment by MasterCruelty** [comment]
> I honestly never tried it. Why don't you `os.system( "zip -r {}/file.zip args".format( os.getcwd() ) )`?

mmmh if I want to create a .sh file and execute it via os, is it right to do this?
```ruby
path = os.getcwd()
os.system("cd " + path)
os.system("bash <filename>.sh")   # or os.system("cd " + path + " | bash <filename>.sh")
```

**Comment by archetipico** [comment]
I don't know if the `cd` approach would work.
Plus, why don't you just `bash path/file.sh`?
